`define MODULE_NAME FFT_Top
`define TARGET_DEVICE_GW2A_18C
`define FIXED
`define FFT4096
`define POINTS 4096
`define POINTS_LOG 12
`define LOW_RESOURCE
`define MODE_FORWARD
`define OUTPUT_NATURAL
`define SCALING_RS111
`define INPUT_DATA_WIDTH 8
`define INPUT_DATA_WIDTH_LOG 3
`define TWIDDLE_FACTOR_WIDTH 16
`define TWIDDLE_FACTOR_WIDTH_LOG 4
`define OUTPUT_DATA_WIDTH 8
`define OUTPUT_DATA_WIDTH_LOG 3
`define REDUCTION_ROUNDING
`define DSP_BLOCK_BASED
`define EBR_MEMORY
`define TDF_EBR_MEMORY
